"use client"
import React from 'react';
import store from '../store/store';
import './globals.css'
import { Inter } from 'next/font/google'
import Header from '@/components/Header'
import { useEffect } from 'react'
import { access_token } from '@/utils/constants'
import Providers from '@/store/Provider';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {


  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers store={store}>
          <Header />
          <main className='w-full'>
            {children}
          </main>
        </Providers>
      </body>

    </html>
  )
}
